Support list for `opensearch_version` in PluginStats
opensearch-project/opensearch-net pull request #568
Opened 2024-02-29 23:03 UTC by Xtansia

### Description
Support list for `opensearch_version` in PluginStats. Fixes failing tests against unreleased OpenSearch `2.x` & `main`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-01 17:51 UTC, dblock approved these changes

2024-03-01 17:51 UTC, dblock requested changes
Is there a breaking change being introduced in 2.13? That shouldn't be the case.

2024-03-03 22:21 UTC, Xtansia commented
> Is there a breaking change being introduced in 2.13? That shouldn't be the case.

It's a result of this backport: https://github.com/opensearch-project/OpenSearch/pull/12271

2024-03-04 21:05 UTC, dblock commented
It's a bug, I opened https://github.com/opensearch-project/OpenSearch/issues/12528. Can we avoid this breakage in a different way (mark it pending?).

2024-03-04 21:13 UTC, Xtansia commented
> It's a bug, I opened [opensearch-project/OpenSearch#12528](https://github.com/opensearch-project/OpenSearch/issues/12528). Can we avoid this breakage in a different way (mark it pending?).

What exactly do you mean by "mark it pending"? Change the PR to Draft? As presumably we'll still need these changes as the breakage will remain in 3.x?

2024-03-04 21:18 UTC, dblock commented
> What exactly do you mean by "mark it pending"? Change the PR to Draft? As presumably we'll still need these changes as the breakage will remain in 3.x?

I mean our build is broken here without this change and we need a workaround, not support for an array. I believe that was a side-effect/mistake and we will not be making a breaking change in 3.0, but I could be wrong.

2024-03-24 22:15 UTC, closed without merging