Update API generator to use new OpenAPI specification
opensearch-project/opensearch-net pull request #609
Opened 2024-04-16 01:04 UTC by Xtansia

### Description
Update API generator to use new OpenAPI specification

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-16 11:40 UTC, dblock requested changes
There are a few changes here that looks breaking API-wise, e.g. `HealthStatus` replaces `WaitForStatus`, etc. 

Either bump major version in this PR and add UPGRADING.md, or add backwards compatible code?

2024-04-16 11:40 UTC, dblock commented on src/OpenSearch.Net/Api/Enums.cs
> -	}
Is this a breaking API change?

2024-04-16 11:40 UTC, dblock commented on src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Cluster.cs
> -        /// <summary>Specify the level of detail for returned information.</summary>
Another potentially breaking change.

2024-04-16 22:25 UTC, Xtansia commented
> There are a few changes here that looks breaking API-wise, e.g. `HealthStatus` replaces `WaitForStatus`, etc.
> 
> Either bump major version in this PR and add UPGRADING.md, or add backwards compatible code?

`main` is already developing the next major version (2.x) and includes other breaking changes. I'll make an UPGRADING.md

2024-04-17 10:23 UTC, dblock approved these changes

2024-04-17 10:23 UTC, merged