Add UPGRADING.md to document breaking changes
opensearch-project/opensearch-net pull request #618
Opened 2024-04-23 02:57 UTC by Xtansia

### Description
Add UPGRADING.md to document breaking changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-23 13:31 UTC, dblock requested changes
Add a link to UPGRADING in README.md. In [other projects](https://github.com/ruby-grape/grape?tab=readme-ov-file#stable-release) I've seen things like "You are reading the documentation for the next release of X. See [UPGRADING](UPGRADING.md) for upgrading from a previous version.", but an entry in the list of the links would suffice too.

2024-04-23 13:31 UTC, dblock commented on UPGRADING.md
> +
Remove double space.

2024-04-23 13:31 UTC, dblock commented on UPGRADING.md
> +# Upgrade Guidance
I would say "Upgrading OpenSearch.Net" here.

Add an empty line after ;)

2024-04-24 00:03 UTC, dblock approved these changes

2024-04-24 00:03 UTC, dblock commented
tests are failing ...

2024-04-24 00:08 UTC, Xtansia commented
> tests are failing ...

@dblock Failing tests are unrelated one is a known flaky test (#443) others are breakages from building the unreleased k-nn plugin

2024-04-24 00:25 UTC, merged