[BUG] Deadlock prone code in HttpConnection.cs #689
opensearch-project/opensearch-net pull request #737
Opened 2024-08-01 09:19 UTC by DavidPoulsenHGS

### Description
Fixes deadlock prone code in HttpConnection.cs. Changed synchronous methods in HttpConnection.cs to use Task.Run/Task.Wait to avoid deadlocks in accordance with: https://learn.microsoft.com/en-us/archive/blogs/jpsanders/asp-net-do-not-use-task-result-in-main-context

### Issues Resolved
#689

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-02 18:31 UTC, joefeser requested changes

2024-08-02 18:31 UTC, joefeser commented on src/OpenSearch.Net/Connection/HttpConnection.cs
> +                    var task = Task.Run(() => responseMessage.Content.ReadAsStreamAsync());
have you considered just changing it to responseMessage.Content.ReadAsStreamAsync().ConfigureAwait(false)?

2024-08-02 18:31 UTC, joefeser commented on src/OpenSearch.Net/Connection/HttpConnection.cs
> +                    var task = Task.Run(() => client.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead));
have you looked at using client.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false)?

2025-05-13 17:05 UTC, Salgat commented on src/OpenSearch.Net/Connection/HttpConnection.cs
> +                    var task = Task.Run(() => client.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead));
@joefeser  .ConfigureAwait(false) is not needed inside a Task.Run since there is no synchronization context to capture.

2025-05-13 17:12 UTC, Salgat commented
Using .GetAwaiter().GetResult() in a library is considered a massive problem since it does open the door to deadlock. As a last resort, Task.Run(...).Wait() is definitely better than the current .GetAwaiter().GetResult(), but the more appropriate option is to remove the synchronous logic altogether if it's just wrapping an async call in a synchronous wait. At that point, the user of the library can do that themselves using their own judgment on whether it's necessary and with full knowledge of what is happening.

2026-07-10 19:54 UTC, SamuelCox commented
Hey all, this is a very old PR, I'd like to attempt to get opensearch-net into a very clean slate so unless someone protests I will delete close this PR within a few days. We can create a new issue or new pr for the underlying issue once we've tackled higher priority stuff.

2026-07-18 14:45 UTC, closed without merging